example_list = ['apple', "banana", "cherry"]
print("Print All element from list")
print(example_list) 
print("Access element by index")
print(example_list[2])
print("Access element from last")
print(example_list[-1])
print("Specify the range for accessing list element")
example_list = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
print(example_list[2:5])
print("start from first element")
print(example_list[:2])
print("Start from spacify element and end with last element")
print(example_list[6:])
print("Enter a element on specific index")
example_list[1] = "blackcurrant"
print(example_list) 
print("itrate element using for loop")
for item in example_list:
    print(item) 
print("Print length of list")
print(len(example_list))
print("Add element at last using append method")
example_list.append("chiku")
print(example_list) 
print("Add element at specific possion")
example_list.insert(2,"tomato")
print(example_list) 
print("Remove Specific element")
example_list.remove("tomato")
print(example_list) 
print("Remove element from spacific index")
example_list.pop(0)
print(example_list) 
print("copy a list and print")
newList=example_list.copy()
print(newList)
print("joined multiple list")
list3=example_list+newList
print(list3)
print("Create a list using constructor")
example_list = list(("apple", "banana", "cherry"))
print(example_list)